#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch polybar
export PRIMARYMONITOR=$(xrandr -q | grep -w connected | grep -w primmary | grep -o '^\S*')
polybar main -c ~/.config/bspwm/polybar/config &

export SECONDARYMONITOR=$(xrandr -q | grep -w connected | grep -v primary | grep -o '^\S*')
if [[ $SECONDARYMONITOR != "" ]]; then
    polybar secondary -c ~/.config/bspwm/polybar/config &
fi
