
helper: helper.c cpu.h sketchybar.h wattage.h
	clang -std=c99 -O3 helper.c -o helper -framework IOKit

helper: helper.c cpu.h sketchybar.h wattage.h
	clang -std=c99 -O3 helper.c -o helper -framework IOKit