#!/usr/bin/env sh

# General Icons
LOADING=􀖇
APPLE=􀣺
PREFERENCES=􀺽
ACTIVITY=􀒓
LOCK=􀒳
BELL=􀋚
BELL_DOT=􀝗

# Git Icons
GIT_ISSUE=􀍷
GIT_DISCUSSION=􀒤
GIT_PULL_REQUEST=􀙡
GIT_COMMIT=􀡚
GIT_INDICATOR=􀂓

# Spotify Icons
SPOTIFY_BACK=􀊎
SPOTIFY_PLAY_PAUSE=􀊈
SPOTIFY_NEXT=􀊐
SPOTIFY_SHUFFLE=􀊝
SPOTIFY_REPEAT=􀊞

# Yabai Icons
YABAI_STACK=S
YABAI_FULLSCREEN_ZOOM=􀏜
YABAI_PARENT_ZOOM=􀥃
YABAI_FLOAT=F
YABAI_GRID=G

#Cpu Usage
ICON_CPU=󰍛

#Wattage
ICON_BOLT=󱐋

# Spotify
ICON_SPOTIFY=󰓇
ICON_SPOTIFY_PAUSE_BAR=󰏤
ICON_SPOTIFY_PLAY_BAR=󰐊

# Volume
VOLUME_HIGH=󰕾
VOLUME_MEDIUM=󰖀
VOLUME_MUTED=󰖁

# Battery
ICON_BATTERY_FULL=󰁹
ICON_BATTERY_90=󰂂
ICON_BATTERY_80=󰂁
ICON_BATTERY_70=󰂀
ICON_BATTERY_60=󰁿
ICON_BATTERY_50=󰁾
ICON_BATTERY_40=󰁽
ICON_BATTERY_30=󰁼
ICON_BATTERY_20=󰁻
ICON_BATTERY_10=󰁺
ICON_BATTERY_FULL_CHARGING=󰂅
ICON_BATTERY_90_CHARGING=󰂋
ICON_BATTERY_80_CHARGING=󰂊
ICON_BATTERY_70_CHARGING=󰢞
ICON_BATTERY_60_CHARGING=󰂉
ICON_BATTERY_50_CHARGING=󰢝
ICON_BATTERY_40_CHARGING=󰂈
ICON_BATTERY_30_CHARGING=󰂇
ICON_BATTERY_20_CHARGING=󰂆
ICON_BATTERY_10_CHARGING=󰢜

# Calendar
ICON_CALENDAR=󰸗

# Clock
ICON_CLOCK=󰅐