#!/usr/bin/env sh
source "$HOME/.config/sketchybar/state.sh"
source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items" 

DATA_ICON_PADDING_RIGHT=3
DATA_BACKGROUND_PADDING_LEFT=7
DATA_ICON_PADDING_LEFT=3
DATA_LABEL_PADDING_RIGHT=5
BORDER_SELECTED_WIDTH=2

hinit spaces

HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

FONT="JetBrainsMono Nerd Font"
FONT_ICON="Material Design Icons:Bold:12.0"
PADDINGS=1

sketchybar --bar     height=32                        \
                     color=$TRANSPARENT               \
                     shadow=on                        \
                     position=top                     \
                     sticky=off                       \
                     padding_right=0                  \
                     padding_left=0                   \
                     corner_radius=0                  \
                     margin=-8                        \
                     blur_radius=0                    \
                     notch_width=0                    \
           --default                                  \
                     icon.font="$FONT_ICON"           \
                     icon.y_offset=3                  \
                     label.font="$FONT:SemiBold:10.0"  \
                     label.y_offset=3                 \
                     background.y_offset=3            \
                     background.height=21


# Left
source "$ITEM_DIR/spaces.sh"

# Right
source "$ITEM_DIR/data_spacer.sh"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/wattage.sh"
source "$ITEM_DIR/spotify.sh"
source "$ITEM_DIR/brackets.sh"

sketchybar --update

echo "sketchybar configuation loaded.."