[icons]
# font awesome
TelegramDesktop = ""
firefox = ""
Alacritty = ""
Termite = ""
Thunderbird = ""
Gpick = ""
Nautilus = "📘"
# smile emoji
MyNiceProgram = "😛"
Code = ""
discord = ""

[aliases]
TelegramDesktop = "Telegram"
"Org\\.gnome\\.Nautilus" = "Nautilus"

[general]
separator = " "
default_icon = ""
wm_property = "class"

[options]
remove_duplicates = false
no_names = true
no_icon_names = false